version: '3.7'
services:
  movies:
#    image: ghcr.io/eduardman/movies:latest
#    build: .
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - CATALINA_OPTS=-DJDBC_DATABASE_URL='jdbc:postgresql://db:5432/movies?user=app&password=pass'
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - 5000:5432
    environment:
      - POSTGRES_DB=movies
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro